// Question types ("patterns") for each Arithmetic topic. The AI classifies every uploaded
// question into one of these, or proposes a new one, so students can practise the same type.
export const PATTERNS = {
  'Percentages': [
    ['Basic percentage calculation', 'x% of a number, or what percent one number is of another'],
    ['Successive percentage change', 'two or more % increases/decreases applied one after another'],
    ['Percentage more or less than', 'A is x% more than B; by what % is B less than A, or chained comparisons'],
    ['Price rise and consumption', 'how much to cut consumption to keep spending the same'],
    ['Price drop buys more', 'a % price cut lets you buy extra quantity for the same money'],
    ['Income spent in stages', 'percentages of the remaining amount spent step by step, savings known'],
    ['Pass-fail overlap', 'percent failing one, other or both subjects (sets with percentages)'],
    ['Price change versus sales and revenue', 'price cut or rise with a change in units sold and revenue'],
    ['Elections and votes', 'turnout, invalid votes, winning margin, number of voters'],
    ['Marks and percentages', 'pass marks, averages and percentages of students in exams'],
    ['Percentage change in a product', 'length x breadth, price x quantity, radius squared: combined % change'],
  ],
  'Profit & Loss': [
    ['Selling price from profit percent', 'find SP, CP or profit % directly'],
    ['Cost of x items equals selling price of y', 'profit or loss % from item counts'],
    ['Mark-up and discount', 'tag price, discount and profit, including trade discounts'],
    ['Loss-to-gain swing', 'selling for a bit more changes a loss into a gain; find cost'],
    ['Chain of resales', 'an item resold several times at different profits or losses'],
    ['Same selling price, profit and loss', 'two items sold at the same price, one at a gain and one at a loss'],
    ['Dishonest weights', 'false weights or measures, with or without mark-up and discount'],
    ['Revenue maximisation', 'price rise reduces sales; find the best price or maximum revenue'],
    ['Break-even and fixed costs', 'fixed and per-unit costs, units needed for a target profit'],
    ['Successive discounts', 'two or three discounts one after another; single equivalent discount'],
    ['Free items and offers', 'buy x get y free, extra items for the price of a dozen, effective discount or profit'],
  ],
  'SI & CI': [
    ['Simple interest basics', 'SI, rate, time or principal from the formula'],
    ['Compound interest amount', 'CI amount, including half-yearly or quarterly compounding and comparisons'],
    ['CI minus SI', 'difference between CI and SI over 2 or 3 years'],
    ['Doubling and growth multiples', 'a sum doubles or triples; when will it become k times'],
    ['Amounts over different years', 'amounts after n and m years given; find rate or principal'],
    ['Sum split across rates', 'a sum divided into parts at different rates or times'],
    ['Instalments', 'equal instalments to repay a loan at SI or CI'],
    ['Population growth and decline', 'population or value changing by different % each year'],
    ['Effective rate of interest', 'half-yearly or quarterly compounding expressed as a yearly rate'],
  ],
  'Ratio & Proportion': [
    ['Dividing in a ratio', 'split an amount in a given ratio'],
    ['Combining ratios', 'A:B and B:C to A:B:C or A:C'],
    ['Adding to both terms', 'number added to or subtracted from both terms to get a new ratio'],
    ['Incomes, expenses and savings', 'income and expenditure ratios with equal or known savings'],
    ['Ages in ratio', 'ratio of ages now and after or before some years'],
    ['Coins in a ratio', 'coins of different values in a ratio with a known total'],
    ['Partnership profit sharing', 'capital times time decides each partner\'s share'],
    ['Direct and inverse variation', 'x varies directly or inversely as y and z'],
    ['Value proportional to square', 'value varies as square of weight; loss when broken'],
    ['Fixed plus variable cost', 'cost partly fixed and partly proportional to one or more quantities'],
  ],
  'Averages': [
    ['Basic average', 'average of a list of numbers'],
    ['Adding or replacing a member', 'a person joins, leaves or is replaced and the average changes'],
    ['Weighted average of groups', 'combining or removing groups with known averages'],
    ['Batting and bowling averages', 'runs per innings or per wicket changing after a match'],
    ['Overlapping groups', 'average of first k and last k items sharing a middle item'],
    ['Correcting a wrong entry', 'one value was misread; find the correct average'],
    ['Increasing some, decreasing others', 'some items raised, others lowered; find how many'],
    ['Ages and averages over time', 'family average age now and years ago, with a birth or death'],
    ['Consecutive numbers', 'averages of consecutive integers or multiples'],
  ],
  'Mixtures & Alligation': [
    ['Mean price or concentration', 'price or strength of a mixture from its parts'],
    ['Alligation ratio', 'ratio or quantity needed to reach a target price, strength or profit'],
    ['Changing milk-water ratio', 'adding water or mixing two mixtures to change the ratio'],
    ['Evaporation and concentration', 'removing water to raise strength'],
    ['Repeated replacement', 'taking out part of a mixture and replacing it, possibly several times'],
    ['Blend price with profit', 'mixture sold at a profit; find a component price'],
    ['Three-way mixture', 'three ingredients at different prices or strengths'],
  ],
  'Time & Work': [
    ['Working together', 'combined time of two or more workers, including efficiency ratios'],
    ['Finding one worker\'s time', 'combined time and one worker\'s time known; find the other'],
    ['Someone leaves midway', 'workers leave or join partway through the job'],
    ['Man-days and hours', 'workers x days x hours scaling, extra workers joining'],
    ['Wages by work share', 'pay split according to work done'],
    ['Men versus women efficiency', 'groups of men, women or children with equivalent work'],
    ['Pipes and leaks', 'filling and emptying pipes, leaks'],
    ['Alternate days', 'workers working on alternate days or in turns'],
    ['Efficiency chains', 'A is x% more efficient than B, and so on'],
    ['Together-time shortcut', 'each takes x and y more than together: t = root(xy)'],
    ['Efficiency changes midway', 'a worker or machine speeds up or slows down partway through'],
    ['Work with breaks or holidays', 'days off, Sundays or rest days stretch the calendar time'],
  ],
  'Time, Speed & Distance': [
    ['Basic speed, time, distance', 'unit conversion and direct speed-time-distance'],
    ['Average speed', 'average speed over equal distances or several legs'],
    ['Late and early arrival', 'different speeds make someone late or early'],
    ['Speed change saves time', 'faster speed saves time; find usual speed'],
    ['Trains crossing', 'trains passing poles, platforms or each other'],
    ['Meeting and relative speed', 'two objects moving towards each other or meeting again'],
    ['Boats and streams', 'upstream, downstream, still-water and current speed'],
    ['Races', 'head starts and race margins between runners'],
    ['Circular tracks', 'runners on a circular track meeting'],
    ['Stoppages', 'average speed with and without stops'],
    ['Escalators', 'walking on a moving escalator, counting steps'],
    ['Chase and head start', 'one starts later and catches up; police chase, delayed starts with stops'],
  ],
};

export const PATTERN_HINTS = Object.fromEntries(
  Object.values(PATTERNS).flat().map(([n, h]) => [n, h])
);
